[package]
name = "publish-web-project"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pwp"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.20", features = ["derive", "help", "usage", "suggestions", "wrap_help", "error-context", "color"] }
progressing = "3.0.2"
ssh2 = "0.9.4"